### ISSUE TITLE
ansible errors

### ISSUE THREAD

**Issue by derekyau** [newrelic/infrastructure-agent-ansible#1]
I am trying to run this on CentOS RHEL and I seem to run into an error at the following place in the script:

```
- name: setup agent repo reference
  yum_repository:
    baseurl: "https://download.newrelic.com/infrastructure_agent/linux/yum/el/{{ os_version }}/x86_64"
    gpgcheck: yes
    gpgkey: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    name: 'New-Relic-Infrastructure'
    repo_gpgcheck: yes
    state: present
    description: New Relic Infrastructure
  when: os_name|lower == 'redhat'
```

the error in the console is:

```
FAILED! => {"failed": true, "reason": "no action detected in task. This often indicates a misspelled module name, or incorrect module path.\n\nThe error appears to have been in '/Users/derek/work/project_path/ansible/roles/infra-agent-ansible/tasks/agent.yml': line 32, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: setup agent repo reference\n  ^ here\n"}
```

I can't seem to figure out what's wrong? I just downloaded this repo from master and put it in my `./roles`
