### ISSUE TITLE
Guidance for a PR to add integration configuration to the playbook

### ISSUE THREAD

**Issue by RulerOf** [newrelic/infrastructure-agent-ansible#163]
## Is your feature request related to a problem? Please describe.
This playbook has vars for configuring the agent itself and _installing_ integrations, but the readme doesn't even mention the topic of **configuring** integrations (e.g. `/etc/newrelic-infra/integrations.d/nginx-config.yml`), let alone support them in any way that I can determine.

I'd like to submit an already-developed patch for this feature, but it's unclear to me why the topic is not covered in the readme. Was integration configuration left out intentionally?

## Feature Description
Add a top-level var `nrinfragent_integration_config` that accepts a list of integration configuration filenames and their contents as YAML, which are rendered into files in the proper folder by the playbook. An example config would be:

```yaml
nrinfragent_integration_config:
  - filename: nginx-config.yml
    content:
      integrations:
        - name: nri-nginx
          env:
            METRICS: "true"
            STATUS_URL: http://127.0.0.1/nginx_status
            STATUS_MODULE: discover
            REMOTE_MONITORING: true
          interval: 30s
        - name: nri-nginx
          env:
            INVENTORY: "true"
            STATUS_URL: http://127.0.0.1/nginx_status
            CONFIG_PATH: /etc/nginx/nginx.conf
            REMOTE_MONITORING: true #new users should leave remote_monitoring = true
          interval: 60s
          inventory_source: config/nginx
```

This var would be processed by a playbook task, writing `nginx-config.yml` to the proper location for the installed version of the agent.

## Describe Alternatives
I considered writing a separate task for writing agent configs, but I can't come up with a good reason that this playbook shouldn't do it.

## Additional context
I have this working right now, but will need to spend time developing the test suite. If you have any suggestions surrounding the topic (including if you don't want to add the feature!) please let me know.

## Priority
Really Want

----

Edit: Switched from `config` to content as a name for the key representing file contents
