### ISSUE TITLE
Docs for custom_attributes not correct

### ISSUE THREAD

**Issue by andy-isoc** [newrelic/infrastructure-agent-ansible#181]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
The documentation for the `custom_attributes` var for the role is incorrect. The simplest example is missing an indent.

## Expected Behavior
```yaml
---
- hosts: ap_ne_1
  roles:
    - name: newrelic.newrelic-infra
      vars:
        log_file: /opt/logs/newrelic-infra.log
        verbose: 0
        nrinfragent_config:
          license_key: 12345
          custom_attributes:
            environment: dev
```
