### ISSUE TITLE
logging both Linux and Windows

### ISSUE THREAD

**Issue by Hokwang** [newrelic/infrastructure-agent-ansible#190]
logging both Linux and Windows

## Description
When use path variable, please consider both Linux and Windows case.

In my case, I have both OS and need to settings like,
```
<Windows> C:\Program Files\New Relic\newrelic-infra\logging.d\logging.yml
logs:
  - name: app
    file: C:\newrelic-log\*

<Linux> /etc/newrelic-infra/logging.d/logging.yml
logs:
    - name: app
      file: /var/log/newrelic-log/*
```

Your code has only one variable for this.
I think you need to split variable for each OS.

## Expected Behavior
User can set up logging.yml for both OS.
