### ISSUE TITLE
ansible_version.full is compare with a string and not a semver value

### ISSUE THREAD

**Issue by nordri** [newrelic/infrastructure-agent-ansible#196]
Hello there!

## Description
We notice that the comparison between `ansible_version.full` and "2.8.0" is happening as strings and the task executed is not the one that should be executed.

## Expected Behavior
The task to be executed should be the one with the right Ansible version.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
For example, [this](https://github.com/newrelic/infrastructure-agent-ansible/blob/master/tasks/install_dist_pkgs.yml#L2-L6) task is executed when Ansible version is 2.10.7 because the comparison is true at string level, the string "2.8.0" is higher than 2.10.0.

## Steps to Reproduce
Just run the role with Ansible version 2.10.0 or even 2.11.0

## Your Environment
I'm using version 0.10.3 but this bug affects all versions. Ansible version 2.10.7

## Additional context
To fix the issue I can suggest this change:
```
- name: confirm redhat lsb util is present pre2.8.0
  yum:
    name: redhat-lsb-core
    state: present
  when: nrinfragent_os_name != 'windows' and ansible_version.full is version("2.8.0", "<")
```

Thanks a lot.
