### ISSUE TITLE
Logging is broken because `td-agent-bit` is missing

### ISSUE THREAD

**Issue by GarrisonD** [newrelic/infrastructure-agent-ansible#202]
## Description

I configured logging in New Relic agent properly, but there were still no logs in UI. After some investigation, I figured out that `td-agent-bit` executable is missing.

I fixed the issue by installing it manually.

## Expected Behavior

The role installs `td-agent-bit` at least when in configuration there are some logging entries with `type: file`.

## Steps to Reproduce

Run the role with:

```
nrinfragent_logging:
  - name: syslog
    file: /var/log/syslog
    attributes: { logtype: linux_messages }
```

## Your Environment

Ubuntu 22.04 LTS

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*
