### ISSUE TITLE
dump_all() got an unexpected keyword argument 'sort_keys'

### ISSUE THREAD

**Issue by grommir** [newrelic/infrastructure-agent-ansible#207]
## Description
Got error while trying to set up a `nrinfragent_logging`
```
dump_all() got an unexpected keyword argument 'sort_keys'
```

## Steps to Reproduce
Use playbook

```yaml
# code: language=ansible
---
- hosts: all
  roles:
    - role: newrelic.newrelic-infra
      become: true
      vars:
        nrinfragent_config:
          license_key: "{{ nr_license_key }}"
        nrinfragent_logging:
          - name: example-log
            file: /var/log/example.log

```

## Your Environment

Amazon Linux2
