### ISSUE TITLE
Ansible 2.8 - Jinja undefined values changed

### ISSUE THREAD

**Issue by jygastaud** [newrelic/infrastructure-agent-ansible#74]
## Issue

Using Ansible 2.8, the following test to `nrinfragent_license_key` always consider as true.

```
{% if nrinfragent_license_key is defined %}
license_key: {{ nrinfragent_license_key }}
{% endif %}
```

## Current result

```
$ cat /etc/newrelic-infra.yml 
license_key: ************
log_file: /var/log/nr-infra.log
log_to_stdout: false

license_key: 
```

## Expected result

```
$ cat /etc/newrelic-infra.yml 
license_key: ************
log_file: /var/log/nr-infra.log
log_to_stdout: false 
```

## Proposed change

```
{% if nrinfragent_license_key %}
license_key: {{ nrinfragent_license_key }}
{% endif %}
```

## Reference

https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.8.html#jinja-undefined-values

**Comment by davidbrota** [comment]
Hello,

I've tried to replicate with no success the behavior you are describing. Can you provide more details on your environment? (OS, Ansible version, playbook, etc.).

**Comment by jygastaud** [comment]
Hi @davidbrota 

I try to move my Ansible version to 2.7 and it also failed to detect correctly the `is defined` so it must be something else... maybe related to the fact that `nrinfragent_license_key: null` is set as default.
Maybe that issue is related to the issue : https://github.com/ansible/ansible/issues/37441

However, here is some more details about the actual config.

## Local informations

```
$ uname -a
Linux 4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ ansible --version
ansible 2.8.0
  config file = /home/jyg/workspace/cleverage/xxx/xxxx/ansible.cfg
  configured module search path = [u'/home/jyg/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jyg/.local/share/virtualenvs/xxxx-XW89vaJr/local/lib/python2.7/site-packages/ansible
  executable location = /home/jyg/.local/share/virtualenvs/xxxx-XW89vaJr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

```
$ cat ansible.cfg
[defaults]
roles_path = ./provisioning/roles

[ssh_connection]
pipelining = True
control_path = /tmp/ansible-ssh-%%h-%%p-%%r
```

```
$ cat requirements.yml
# from galaxy
- src: newrelic.newrelic-infra
```

## Destination

```
$ uname -a
Linux 4.4.0-154-generic #181-Ubuntu SMP Tue Jun 25 05:29:03 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## Playbook

```
---
- hosts: all
  become: yes
  become_user: root

  pre_tasks:
      - name: Define config_dir.
        set_fact:
          config_dir: "../config"
        when: config_dir is not defined
        tags: ['always']

      - include_vars: "{{ item }}"
        with_fileglob:
          - "{{ config_dir }}/config.yml"
        tags: ['always']

  roles:
    - { role: newrelic.newrelic-infra, tags: ["monitoring", "infra"] }

```

## config.yml (sample)

```
newrelic_license_key: XXXXXXX
nrinfragent_config:
  license_key: "{{ newrelic_license_key }}"
  log_file: /var/log/nr-infra.log
  log_to_stdout: false
nrinfraintegrations_state: latest
nrinfragent_integrations:
  - { name: nri-apache, state: "latest" }
```
