### ISSUE TITLE
'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'key' when attempting to install via tarball

### ISSUE THREAD

**Issue by nc-fosterr** [newrelic/infrastructure-agent-ansible#89]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
Unable to install newrelic-infra from tarball archive

## Expected Behavior
I should be able to install newrelic tarball archive

## [Troubleshooting]

The  playbook returns with:

```
TASK [newrelic-infra : save config options to file] ****************************
fatal: [localhost]: FAILED! =>
  msg: |-
    The task includes an option with an undefined variable. The error was: 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'key'
    The error appears to be in '/test/newrelic-infra/tasks/install_targz.yml': line 42, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
    The offending line appears to be:
    - name: save config options to file
      ^ here
```

## Steps to Reproduce

Configure variable to use tarball

```
      vars:
        nrinfragent_tarball_version: "PUTVERSIONHERE"
        nrinfragent_architecture: "PUTARCHHERE"
```

## Your Environment
Ubuntu Bionic, ARM64
Ansible 2.10

## Additional context

The error is coming from here:

```
- name: save config options to file
  lineinfile:
    dest: /etc/newrelic-infra.yml
    regexp: "^{{ item.key }}: "
    line: "{{ item.key }}: {{ item.value }}"
    create: yes
  with_items: "{{ lookup('dict', nrinfragent_config) }}"
  notify: restart newrelic-infra
  ```

Interestingly enough, the issue seem that `with_items` does not appear to work as intended, despite documentation stating otherwise. After we change the call to `with_dict`, the role was able to perform a lookup successfully.

**Comment by hackzilla** [comment]
@nc-fosterr I've tried to use `with_dict`, which did suppress the error.
However, if you look at `/etc/newrelic-infra.yml`, then you will see that it has processed the config badly.

This is how it inserted the license code.
```
key: license_key
value: <license code>
```

I'll keep trying different things.

**Comment by nc-fosterr** [comment]
@hackzilla Good catch!

**Comment by JakubKotkowiak** [comment]
Hello @nc-fosterr , thank you for taking the time to create an issue. I was trying to reproduce your issue and it seems to occur only when you don't configure in vars the following section:
```yaml
nrinfragent_config:
          license_key: YOUR_LICENSE_KEY
          log_file: /var/log/nr-infra.log
          log_to_stdout: false
```
So the whole file would like like this:
```yaml
---
- hosts: <target_host>
  roles:
    - name: newrelic.newrelic-infra
      vars:
        nrinfragent_tarball_version: "NR_INFRA_VERSION"
        nrinfragent_architecture: "NR_INFRA_ARCH"
        nrinfragent_config:
          license_key: <NR1_LICENSE_KEY>
          log_file: /var/log/nr-infra.log
          log_to_stdout: false
```
Without this section I've received the same error as you did since ansible is trying to iterate over an item that does not exist, once I've entered this part it went through without a hitch. I've tested this on Ansible 2.10. Please let me know if this resolves your issue, thanks!
